### ISSUE TITLE
Playing sound uses incorrect bus

### ISSUE THREAD

**Issue by bernarma** [missionpinball/mpf-gmc#10]
Using the latest Godot (as of 19/8) when playing a sound from MPF, the incorrect bus is used when NOT specifying a default (as illustrated below).

```
sound_player:
  mode_song1_started:
    song1:
      action: play
```

As configured in Godot
![image](https://github.com/user-attachments/assets/65571117-9647-4fc1-b26c-3bc446414030)

It appears as though the logic when determining the audio bus to use is done prematurely.

```
var bus: GMCBus = self.buses[settings["bus"]] if settings.get("bus") else self.default_bus
```
Note: Not using the wav file configuration as specified in Godot.

In sound_player.gd line 76, the bus is retrieved (which is needed to stop the sound) but the bus retrieved is incorrect as it should also take into account the bus that was used as part of the default configuration for the sound file.

Later on, the value of the bus from the sound file is used but it is ignored as the bus is not retrieved.

```
	for prop in [ "bus", "fade_in", "fade_out", "start_at", "max_queue_time"]:
		# Any values passed from the event have priority, only populate
		# asset property values not defined from the event.
		if settings.get(prop) == null and config.get(prop):
			settings[prop] = config[prop]
```

You can see that the bus value is retrieved... but there is no reassignment of this value - this is the line that uses the existing bus but the incorrect one.

```
		bus.play(file, settings)
```

Hopefully it explains the issue clearly.

The question is, is this correct behavior or not? If not, I can work on a solution to it but need to check first.

**Comment by avanwinkle** [comment]
Thank you for identifying and researching the issue! You are correct, the assignment of the default bus is premature because it's setting a value for bus, so the `MPFSoundAsset` value will never be used since it only overwrites un-set values. The logic here was that any values sent with the event from the `sound_player:` config would override the built-in settings, but using a default bus should not be considered an override.

The code block for stopping is up top to prevent unnecessary calculations on the config that won't be used, and that requires the bus calculation to be before that. But you're right, that also means that the `MPFSoundAsset.bus` property will never be used for stopping, and that's problematic.

So I think the solution should be to move the default bus/action fallbacks and stop behavior (lines 76-83) down _below_ the config assembly block (lines 85-108) so that the config is fully populated before attempting fallbacks. There may also be the same bug in the `fade_out` property when stopping, since the stop is called before that value would be populated from the `MPFSoundAsset`.

If you're comfortable giving it a go, feel free to try out a fix and open a PR for it! Otherwise I'll find some time this week to work on it.

**Comment by bernarma** [comment]
I'll have a go at fixing it but since I've got a workaround, I'll use that for the meantime, and when I get a free moment I'll get it fixed.

**Comment by bernarma** [comment]
Here is the PR
https://github.com/missionpinball/mpf-gmc/pull/11

**Comment by avanwinkle** [comment]
Also fixed! 🥳
