### ISSUE TITLE
settings priority accessor should use dictionary.get

### ISSUE THREAD

**Issue by mpcarr** [missionpinball/mpf-gmc#2]
gmc crashes with index error when settings priority isn't provided.

https://github.com/missionpinball/mpf-gmc/blob/c60ba72b9644fce9ebd3514f9a71b2c117cbcfe9/addons/mpf-gmc/classes/mpf_scene_base.gd#L44

**Comment by mpcarr** [comment]
> Thank you for this! This had the assumption that slides would come through slide_player in MPF which appends all known fields, but it's much safer to use the getter. Fixed!

Thanks for the fixes, I'm writing a bcp lib to use the gmc from vpx so finding some edge cases.

**Comment by avanwinkle** [comment]
Fantastic, I'd love to see what you put together when it's ready for sharing! 

I've tried poking around in VPX but it was over my head. I'm glad somebody is tackling it, because it's a great program and combining VPX with home-brew projects will be a fantastic way to get more folks into the game! 😀
